### ISSUE TITLE
UI + Mobile

### ISSUE THREAD

**Issue by rxaviers** [jquery/download.jqueryui.com#177]
_"Share the download builder between UI and Mobile"_ discussion.
![screenshot](https://f.cloud.github.com/assets/967155/1481584/6d7f84b4-46cc-11e3-8844-9282d26f6383.png)

Action items:
- [x] jQuery UI: Include CSS dependency-comments;
- [x] [#1379](https://github.com/jquery/jquery-ui/pull/1379) jQuery UI: Handle manifest info from JS comments;
- [x] #178 Download Builder: Handle CSS dependencies from JS comments;
- [x] #243 Download Builder: Handle manifest info from JS comments;

Open Questions:
1. Are we going to even both interfaces? Eg:
   - Mobile to include `*.jquery.json` metafiles OR we figure out a simple way to replace the manifest files (`dependencies` could be obtained as input with their AMD dependency tree, but missing how to deduce `name`, `title`, `description`, `docs` link and `category` fields);

Milestone: https://github.com/jquery/download.jqueryui.com/issues?milestone=2&state=open

**Comment by Krinkle** [comment]
Closing as per https://github.com/jquery/download.jqueryui.com/issues/137.
